services:
  nginx-video-server:
    image: tiangolo/nginx-rtmp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1935:1935"
      - "8081:8081"
    volumes:
      - /var/www/jmautomations.nl/videoservidor-srtn/public/ocasionales/:/usr/share/nginx/html/
      - /var/www/jmautomations.nl/videoservidor-srtn/public/ocasionales/hls/:/usr/share/nginx/html/hls
      - /var/www/jmautomations.nl/videoservidor-srtn/public/programas/:/usr/share/nginx/html/programas/
      - /var/www/jmautomations.nl/videoservidor-srtn/public/programas/hls/:/usr/share/nginx/programas/hls
    restart: always
